### ISSUE TITLE
Re Optimization step implementation

### ISSUE THREAD

**Issue by GuyTevet** [DSaurus/threestudio-3dgs#12]
Great work! Thanks guys!

In the optimization step, why did you back prop the SDS and the regularization terms separately instead of adding them up? And why did you update the gaussians in between the two back props?

https://github.com/DSaurus/threestudio-3dgs/blob/1d49c376aab358b9f59ffae5fc2dac9044932ba9/system/gaussian_splatting.py#L129-L140

**Comment by DSaurus** [comment]
Hi @GuyTevet ,

I wrote this because I think regularization losses should not influence the splitting or cloning of Gaussian points. The primary effect of splitting and cloning is to enhance rendering quality, so it should be determined solely by the SDS loss. However, I have not yet ablated it in my experiments, and the properties of 3DGS in generation may not be the same with reconstruction. It's still not sure which way is the more effective for 3DGS splitting and cloning.

**Comment by GuyTevet** [comment]
Got you, that makes sense.
Thanks again for your great work, it helps a lot with my research.
